name: Auto Deploy to Aliyun OSS

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [contentful_update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build
        run: |
          npm install
          node build.js 
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-eu-central-1.aliyuncs.com" 
          access-key-id: ${{ secrets.OSS_ID }}
          access-key-secret: ${{ secrets.OSS_SECRET }}

      - name: Deploy to Aliyun OSS
        run: |
          # 先在日志里打出目录结构，方便排查
          ls -R ./dist/
          # 执行同步，建议加上 --update
          ossutil cp -r ./dist/ oss://mos-surfactant/ -f --update
